<a href="https://colab.research.google.com/github/alfonsocude/MACHINE-LEARNING-1/blob/main/05-%5BTaller%5D-numpy.ipynb#scrollTo=bm0ko4ipL_Ks" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Recuerda que una vez abierto, Da clic en "Copiar en Drive", de lo contrario no podras alamancenar tu progreso**

Nota: no olvide ir ejecutando las celdas de código de arriba hacia abajo para que no tenga errores de importación de librerías o por falta de definición de variables.

# **Taller Numpy** 



1) Importar la libreria numpy y ver la versión que se está usando

In [43]:
import numpy as np
print(np.__version__)

2.1.2


2) Crear un arreglo de tamaño 1D desde 10 hasta 30

In [12]:
a = np.arange(10,31)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

3) Crear un arreglo booleano con valor True de tamaño 4x4

In [7]:
np.full((4,4), True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

4) Generar un arreglo desde el 10 hasta el 30, extraer los elementos pares del arreglo generado.

In [29]:
b= np.arange(10,31,2)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

5) Reemplazar todos los números pares por -1 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando bucles y condicionales.

In [30]:
unos = []
for i in range(len(a)):
    if a[i] in b:
        unos.append(-1)
    if a[i] not in b:
        unos.append(a[i])

np.array(unos)


array([-1, 11, -1, 13, -1, 15, -1, 17, -1, 19, -1, 21, -1, 23, -1, 25, -1,
       27, -1, 29, -1])

6) Reemplazar todos los números pares por -1 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando una función de numpy.

In [34]:
c = np.where(a % 2 == 0,-1,a)
c

array([-1, 11, -1, 13, -1, 15, -1, 17, -1, 19, -1, 21, -1, 23, -1, 25, -1,
       27, -1, 29, -1])

7) Reemplazar todos los números pares por -1 y por 0 los impares de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando bucles y condicionales.

In [33]:
unos = []
for i in range(len(a)):
    if a[i] in b:
        unos.append(-1)
    if a[i] not in b:
        unos.append(0)

np.array(unos)


array([-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,
        0, -1,  0, -1])

8) Reemplazar todos los números pares por -1 y los impares por 0 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando una función de numpy.

In [41]:
np.where(a % 2 == 0,-1,0)


array([-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,
        0, -1,  0, -1])